### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [sarteleb/tc359-project7#1]
I broke it. :cry: It looks like when I try to submit the form with a blank year, I get an `Internal Server Error`. I believe [this resource](http://www.w3schools.com/tags/att_input_required.asp) may help you avoid blank form inputs being submitted.

Let me know when it's updated and I'll take another look.

**Comment by sarteleb** [comment]
Where on codekwondo does it tell me what commands to use when i get that string resource error?  I always forget this.

**Comment by chrisvfritz** [comment]
It's [right here](http://codekwondo.herokuapp.com/skills/37/presentation#/2/1). :smiley:

**Comment by sarteleb** [comment]
Fixed :) Thanks Chris!

**Comment by chrisvfritz** [comment]
:+1: Much better!
